# Zero indexing with lambda

How do we calculate row-wise in Pandas like we do in Excel?

<img src="https://sandeepmj.github.io/image-host/oil-v-gold.png">

We need a couple of new concepts to do this calculation:

1. Capture a number from a cell and hold in variable.
2. We `apply()`calculations across columns, row-wise, using using a `lambda expression`.


This is step one in your ability to accomplish tasks that are highly specialized to your beats.

Link to dataset: https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/oil-v-gold-pandas.csv

In [1]:
## import library
import pandas as pd

In [5]:
## pull in data
df = pd.read_csv ("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/oil-v-gold-pandas.csv")
df

         Date  PX_GOLD  PX_OIL
0     1/31/08    922.7   91.75
1     2/29/08    975.0  101.84
2     3/31/08    916.2  101.58
3     4/30/08    865.1  113.46
4     5/30/08    887.3  127.35
..        ...      ...     ...
116   9/29/17   1281.5   51.67
117  10/31/17   1270.5   54.38
118  11/30/17   1273.2   57.40
119  12/29/17   1309.3   60.42
120   1/31/18   1339.0   64.73

[121 rows x 3 columns]

What are the different values for row **TWO** in this formula for `PX_GOLD`:

$$\text{Pct Chg at time } t = \frac{\text{Value at time } t - \text{Value at start time}}{\text{Value at start time}} \times 100$$

Use `.iat` to store a value from a specific cell into a variable:

```dataframe["column_name"].iat[row_index_number]```

In [7]:
df["PX_GOLD"].iat[0]
float(df["PX_GOLD"].iat[0])

922.7

Also works:

`dataframe.iat[col_index_number, row_index_number]`

In [10]:
gold_baseline = float(df.iat[0,1])
gold_baseline

922.7

Place the value for the starting oil price in a variable called `oil_baseline`

In [14]:
## oil_baseline
df["PX_OIL"].iat[0]
oil_baseline = float(df["PX_OIL"].iat[0])
oil_baseline

91.75

# `lambda expressions`

We're going to just write one first and then break it down:

In [18]:
## create a new column that holds the zero index for gold
df["gold_index"] = df["PX_GOLD"].apply(lambda x: ((x - gold_baseline) / gold_baseline) *100)

df

         Date  PX_GOLD  PX_OIL  gold_index
0     1/31/08    922.7   91.75    0.000000
1     2/29/08    975.0  101.84    5.668148
2     3/31/08    916.2  101.58   -0.704454
3     4/30/08    865.1  113.46   -6.242549
4     5/30/08    887.3  127.35   -3.836567
..        ...      ...     ...         ...
116   9/29/17   1281.5   51.67   38.885878
117  10/31/17   1270.5   54.38   37.693725
118  11/30/17   1273.2   57.40   37.986344
119  12/29/17   1309.3   60.42   41.898775
120   1/31/18   1339.0   64.73   45.117590

[121 rows x 4 columns]

## What  `x` stand for:

- In Pandas, we `apply()` lambda expressions to columns.
-  `.apply()`  works element-wise on each value in the `PX_GOLD` column, one at a time.
- `x` is a single value representing a cell in the column `PX_GOLD`
- The ```lambda x:``` processes each row of a dataframe, one row at a time.
-  The `lambda expression` takes each individual number `x` from `PX_GOLD` and runs the indexing formula on it.

Think of it as: "call each value in `PX_GOLD` as `x`, and do this math to using `x` in the formula."

## create a new column that holds the zero index for oil

In [5]:
## zero index oil

In [19]:
df["oil_index"] = df["PX_OIL"].apply(lambda x: ((x - oil_baseline) / oil_baseline) *100)

df

         Date  PX_GOLD  PX_OIL  gold_index  oil_index
0     1/31/08    922.7   91.75    0.000000   0.000000
1     2/29/08    975.0  101.84    5.668148  10.997275
2     3/31/08    916.2  101.58   -0.704454  10.713896
3     4/30/08    865.1  113.46   -6.242549  23.662125
4     5/30/08    887.3  127.35   -3.836567  38.801090
..        ...      ...     ...         ...        ...
116   9/29/17   1281.5   51.67   38.885878 -43.683924
117  10/31/17   1270.5   54.38   37.693725 -40.730245
118  11/30/17   1273.2   57.40   37.986344 -37.438692
119  12/29/17   1309.3   60.42   41.898775 -34.147139
120   1/31/18   1339.0   64.73   45.117590 -29.449591

[121 rows x 5 columns]

# Homework

<a href="https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/demo-data-solutions/cablebill-v-income.csv">This dataset</a> shows the price of a standard cable subscription and the U.S. median income annually between 1995-2023.

Has median income kept pace with the price of a cable subscription?

Round all numbers to 1 decimal place

Print your findings

In [20]:
## read file
dfb = pd.read_csv ("https://raw.githubusercontent.com/sandeepmj/datasets/refs/heads/main/demo-data-solutions/cablebill-v-income.csv")
dfb

    year  avg_cable_bill  median_household_income
0   1995           22.35                    35249
1   1996           23.28                    36689
2   1997           26.31                    38229
3   1998           27.88                    40148
4   1999           28.94                    41994
5   2000           31.22                    42349
6   2001           33.75                    42710
7   2002           36.47                    43057
8   2003           38.95                    43564
9   2004           41.04                    44684
10  2005           43.04                    46242
11  2006           43.26                    48451
12  2007           47.27                    50740
13  2008           49.65                    52029
14  2009           52.37                    50221
15  2010           54.44                    50046
16  2011           57.46                    50502
17  2012           61.63                    51371
18  2013           69.18                    52250
19  2014           71.45                    53657
20  2015           78.42                    55775
21  2016          150.98                    57617
22  2017          168.49                    61372
23  2018          199.99                    64324
24  2019          210.84                    69560
25  2020          217.42                    67521
26  2021          231.10                    70784
27  2022          251.48                    74580
28  2023          291.81                    75143

In [22]:
## get info
dfb.info()

<class 'pandas.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 3 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   year                     29 non-null     int64
 1   avg_cable_bill           29 non-null     float64
 2   median_household_income  29 non-null     int64
dtypes: float64(1), int64(2)
memory usage: 828.0 bytes

### Index cable billl

In [23]:
## cable_baseline
cable_baseline = float(dfb.iat[0,1])
cable_baseline

22.35

### Index median income

In [24]:
## income_baseline
income_baseline = float(dfb.iat[0,2])
income_baseline

35249.0

In [26]:
dfb["cable_index"] = dfb["avg_cable_bill"].apply(lambda x: ((x - cable_baseline) / cable_baseline) *100)

dfb

    year  avg_cable_bill  median_household_income  cable_index
0   1995           22.35                    35249     0.000000
1   1996           23.28                    36689     4.161074
2   1997           26.31                    38229    17.718121
3   1998           27.88                    40148    24.742729
4   1999           28.94                    41994    29.485459
5   2000           31.22                    42349    39.686801
6   2001           33.75                    42710    51.006711
7   2002           36.47                    43057    63.176734
8   2003           38.95                    43564    74.272931
9   2004           41.04                    44684    83.624161
10  2005           43.04                    46242    92.572707
11  2006           43.26                    48451    93.557047
12  2007           47.27                    50740   111.498881
13  2008           49.65                    52029   122.147651
14  2009           52.37                    50221   134.317673
15  2010           54.44                    50046   143.579418
16  2011           57.46                    50502   157.091723
17  2012           61.63                    51371   175.749441
18  2013           69.18                    52250   209.530201
19  2014           71.45                    53657   219.686801
20  2015           78.42                    55775   250.872483
21  2016          150.98                    57617   575.525727
22  2017          168.49                    61372   653.870246
23  2018          199.99                    64324   794.809843
24  2019          210.84                    69560   843.355705
25  2020          217.42                    67521   872.796421
26  2021          231.10                    70784   934.004474
27  2022          251.48                    74580  1025.190157
28  2023          291.81                    75143  1205.637584

In [27]:
dfb["income_index"] = dfb["median_household_income"].apply(lambda x: ((x - income_baseline) / income_baseline) *100)

dfb

    year  avg_cable_bill  median_household_income  cable_index  income_index
0   1995           22.35                    35249     0.000000      0.000000
1   1996           23.28                    36689     4.161074      4.085222
2   1997           26.31                    38229    17.718121      8.454141
3   1998           27.88                    40148    24.742729     13.898267
4   1999           28.94                    41994    29.485459     19.135295
5   2000           31.22                    42349    39.686801     20.142415
6   2001           33.75                    42710    51.006711     21.166558
7   2002           36.47                    43057    63.176734     22.150983
8   2003           38.95                    43564    74.272931     23.589322
9   2004           41.04                    44684    83.624161     26.766717
10  2005           43.04                    46242    92.572707     31.186700
11  2006           43.26                    48451    93.557047     37.453545
12  2007           47.27                    50740   111.498881     43.947346
13  2008           49.65                    52029   122.147651     47.604187
14  2009           52.37                    50221   134.317673     42.474964
15  2010           54.44                    50046   143.579418     41.978496
16  2011           57.46                    50502   157.091723     43.272150
17  2012           61.63                    51371   175.749441     45.737468
18  2013           69.18                    52250   209.530201     48.231155
19  2014           71.45                    53657   219.686801     52.222758
20  2015           78.42                    55775   250.872483     58.231439
21  2016          150.98                    57617   575.525727     63.457119
22  2017          168.49                    61372   653.870246     74.109904
23  2018          199.99                    64324   794.809843     82.484609
24  2019          210.84                    69560   843.355705     97.338932
25  2020          217.42                    67521   872.796421     91.554370
26  2021          231.10                    70784   934.004474    100.811371
27  2022          251.48                    74580  1025.190157    111.580470
28  2023          291.81                    75143  1205.637584    113.177679

In [28]:
cable_index_2023 = 1205.637584
income_index_2023 = 113.177679

print(f"Cable Index for 2023: {cable_index_2023}")
print(f"Income Index for 2023: {income_index_2023}")

Cable Index for 2023: 1205.637584
Income Index for 2023: 113.177679

In [29]:
## print your findings
print(f"Median income {income_index_2023} has not kept pace with the price of a cable subscription{cable_index_2023}")

Median income 113.177679 has not kept pace with the price of a cable subscription1205.637584